query GetOrderResponse($responseId: String!) {
    getOrderResponse(responseId: $responseId) {
        data {
            id
            attachments {
                name
                location
                key
                mimeType
            }
            comments
            answer
            responseType
            createdAt
            updatedAt
            createdBy {
                id
                email
                firstName
                lastName
                password
                roles {
                    name
                }
                username
                currency
                timezone {
                    value
                    abbr
                    offset
                    isdst
                    text
                    utc
                }
                language
                orders
                responses
                uid
                picture
                iss
                aud
                auth_time
                user_id
                sub
                iat
                exp
                email_verified
                firebase {
                    identities {
                        googlecom
                        email
                    }
                    sign_in_provider
                }
            }
            question {
                title
                orderId
            }
            published
        }
        status
        success
    }
}