query GetPublicOrders($pagination: Pagination, $filter: FilterOrders) {
  getPublicOrders(pagination: $pagination, filter: $filter) {
    docs {
      ...OrderFragment
    }
    totalDocs
    limit
    hasPrevPage
    hasNextPage
    page
    totalPages
    offset
    prevPage
    nextPage
    pagingCounter

  }
}