  query LoggedInUser {
    me {
      email
      firstName
      lastName
      username
      id
      currency
      language
      roles {
        name
        __typename
      }
      timezone {
        value
        text
        abbr
        isdst
        offset
        utc
      }
      profilePic
    }
  }